### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [PhilippeBoisney/LinearProgressBar#3]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by PhilippeBoisney** [comment]
Hey, sorry for the late ! I've just updated it to Swift 3 and also to Cocoapod 👍 
`pod 'LinearProgressBarMaterial'`
Enjoy :)

**Comment by lfarah** [comment]
Thanks, @PhilippeBoisney! 🎉

**Comment by dannysood** [comment]
Why is this issue still open? @lfarah @PhilippeBoisney

**Comment by PhilippeBoisney** [comment]
Because I forgot to close it ;) Thanks !
